# Generated by Django 4.1.4 on 2023-01-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок страницы')),
                ('first_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок первого сравнения')),
                ('first_content', models.TextField(blank=True, verbose_name='Табличка для первого сравнения')),
                ('first_photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Первый график')),
                ('second_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок второго сравнения')),
                ('second_content', models.TextField(blank=True, verbose_name='Табличка для второго сравнения')),
                ('second_photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Второй график')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('content', models.TextField(blank=True, verbose_name='Описание профессии')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('photo_description', models.TextField(blank=True, verbose_name='Описание фото')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FileField(upload_to='photos/%Y/%m/%d', verbose_name='Заголовок в SVG формате')),
                ('logo_field', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Логотип')),
                ('first_menu', models.TextField(max_length=25, verbose_name='Первый пункт меню')),
                ('second_menu', models.TextField(max_length=25, verbose_name='Второй пункт меню')),
                ('thierd_menu', models.TextField(max_length=25, verbose_name='Третий пункт меню')),
                ('fourth_menu', models.TextField(max_length=25, verbose_name='Четвертый пункт меню')),
                ('fifth_menu', models.TextField(max_length=25, verbose_name='Пятый пункт меню')),
                ('all_rights', models.TextField(max_length=150, verbose_name='Пятый пункт меню')),
                ('author', models.TextField(max_length=50, verbose_name='Пятый пункт меню')),
            ],
        ),
    ]
