# Generated by Django 4.1.4 on 2023-01-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок страницы')),
                ('first_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок блока')),
                ('first_content', models.TextField(blank=True, verbose_name='Табличка для блока')),
                ('first_photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
            ],
        ),
    ]
